# FastAgent Configuration File

# Default Model Configuration:
#
# Takes format:
#   <provider>.<model_string>.<reasoning_effort?> (e.g. anthropic.claude-3-5-sonnet-20241022 or openai.o3-mini.low)
# Accepts aliases for Anthropic Models: haiku, haiku3, sonnet, sonnet35, opus, opus3
# and OpenAI Models: gpt-4o-mini, gpt-4o, o1, o1-mini, o3-mini
#
# If not specified, defaults to "haiku".
# Can be overriden with a command line switch --model=<model>, or within the Agent constructor.

default_model: deepseek-chat #xdeepseekv3 #deepseek-chat

# Logging and Console Configuration:
logger:
  level: "debug" #"debug" | "info" | "warning" | "error"
  type: "file" #"none" | "console" | "file" | "http"
  # path: "/path/to/logfile.jsonl"

  # Switch the progress display on or off
  progress_display: true

  # Show chat User/Assistant messages on the console
  show_chat: true
  # Show tool calls on the console
  show_tools: true
  # Truncate long tool responses on the console
  truncate_tools: true

# MCP Servers
mcp:
  servers:
    fetch:
      command: "uvx"
      args: ["mcp-server-fetch"]
    filesystem:
      command: "C:\\Users\\wisdri\\AppData\\Roaming\\nvm\\v22.14.0\\node.exe"
      args:
        [
          "C:\\Users\\wisdri\\AppData\\Roaming\\nvm\\v22.14.0\\node_modules\\@modelcontextprotocol\\server-filesystem\\dist\\index.js",
          ".",
        ]
    webbrowser:
      command: "C:\\Users\\wisdri\\AppData\\Roaming\\nvm\\v22.14.0\\node.exe"
      args:
        [
          "C:\\Users\\wisdri\\AppData\\Roaming\\nvm\\v22.14.0\\node_modules\\@executeautomation\\playwright-mcp-server\\dist\\index.js",
        ]

    v2ex:
      command: "C:\\Users\\wisdri\\AppData\\Roaming\\nvm\\v22.14.0\\node.exe"
      args: ["./node_modules/mcp-server-v2ex/dist/index.js"]
